name: config-snap
base: core20
version: '0.1'
summary: Simple snap which acces keys and secrets shared by the 'content-snap' 
description: |
   The snap just connects to the 'keys' and 'secrets' slot and access the keys and secrets files 
grade: stable
confinement: strict

plugs:
  secrets:
     interface: content
     content: secrets-files
     target: $SNAP/secrets
  keys:
     interface: content
     content: keys-files
     target: $SNAP/keys

parts:
  list-content-secrets:
    source: list-content-secrets
    plugin: dump
  list-content-keys:
    source: list-content-keys
    plugin: dump


apps:
  config-snap-secrets:
    command: list-content-secrets.sh
    daemon: oneshot
  config-snap-keys:
    command: list-content-keys.sh
    daemon: oneshot

